included:
  - SpaceX/Infrastructure/Sources
  - SpaceX/Domain/Sources
  - SpaceX/Presentation/Sources

excluded:
  - SpaceX/Infrastructure/Tests
  - SpaceX/Domain/Tests
  - SpaceX/Presentation/Tests

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - xctfail_message
  - attributes
  - function_default_parameter_at_end
  - nesting
  - large_tuple
  - switch_case_alignment
  - vertical_parameter_alignment_on_call
  - sorted_first_last
  - blanket_disable_command
  - extension_access_modifier

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - force_unwrapping

cyclomatic_complexity: 30
file_length: 500
function_body_length: 150
function_parameter_count: 8

line_length:
  warning: 140
  ignores_comments: true

type_name:
  min_length:
    error: 2
    warning: 3

identifier_name:
  min_length:
    error: 2
    warning: 3
  excluded:
    - id
    - as
    - kN
    - lb
    - kg
    - x
    - y
    - z

number_separator:
  minimum_length: 5

modifier_order:
  preferred_modifier_order: [acl, override, setterACL, dynamic, mutators, lazy, final, required, convenience, typeMethods, owned]

custom_rules:
  closed_brackets_blank_line:
    included: ".*\\.swift"
    name: "blank lines between closed brackets"
    regex: "\\}\n[[[:blank:]]\n]*\n\\}"
    message: "Blank lines between closed brackets should be removed"
    severity: warning

